repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
    - id: pyupgrade
      args: [--py310-plus]
      files: '^(mflike)/.*\.py$'
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix, --config, ./pyproject.toml ]
    - id: ruff-format
      args: [ --config, ./pyproject.toml ]
    