name: Testing tutorial notebooks

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies via pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[all]

    - name: Unit tests
      run: |
        python -m pytest -vv --nbval-lax --cov=mflike --cov-report=xml:coverage.xml

    - name: Report Coverage (codecov)
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
