name: Testing tutorial notebooks

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies via pip
      run: |
        pip install uv
        uv python install ${{ matrix.python-version }}
        uv python pin ${{ matrix.python-version }}
        uv sync --locked --extra all
        uv run cobaya-install mflike.TTTEEE --no-set-global

    - name: Unit tests
      run: |
        uv run pytest -vv --nbval-lax --nbval-current-env --cov=mflike --cov-report=xml:coverage.xml */*.ipynb

    - name: Report Coverage (codecov)
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
