name: Build wheels and upload to PyPI

on: [push, pull_request]

jobs:

  build_upload_dist:
    name: Build source distribution
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        name: Install Python
        with:
          python-version: '3.11'

      - name: Build sdist and wheel
        run: |
          pip install uv
          uv build

      - name: Upload to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        # To test: 
        # export UV_PUBLISH_URL=https://test.pypi.org/legacy/
        run: |
          uv publish
